# Spring settings
spring:
  profiles:
    active: dev

# Huawei Cloud settings
huawei:
  obs:
    endPoint: ${HUAWEI_OBS_END_POINT}
    accessKey: ${HUAWEI_OBS_ACCESS_KEY}
    accessSecretKey: ${HUAWEI_OBS_ACCESS_SECRET_KEY}
    bucketName: ${HUAWEI_OBS_BUCKET_NAME}
    redirectHost: ${HUAWEI_OBS_REDIRECT_HOST}
