# Spring settings
spring:
  profiles:
    active: dev

# Huawei Cloud settings
huawei:
  obs:
    endPoint: ${HUAWEI_OBS_END_POINT}
    accessKeyId: ${HUAWEI_OBS_ACCESS_KEY_ID}
    secretAccessKey: ${HUAWEI_OBS_SECRET_ACCESS_KEY}
